name: Docker Compose Actions Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up network
        run: docker network create wp-network

      - name: Set up database
        run: |
          docker run -d \
            -e MYSQL_ROOT_PASSWORD=1234 \
            -e MYSQL_DATABASE=wordpress \
            --name db \
            --network wp-network \
            mysql:5.7

      - name: Setup WordPress
        run: |
          docker run -d \
            -e WORDPRESS_DB_HOST=db:3306 \
            -e WORDPRESS_DB_USER=root \
            -e WORDPRESS_DB_PASSWORD=1234 \
            -e WORDPRESS_DB_NAME=wordpress \
            -e WORDPRESS_CONFIG_EXTRA="define('WP_SITEURL', 'http://' . \$_SERVER['HTTP_HOST']); define('WP_HOME', 'http://' . \$_SERVER['HTTP_HOST']);" \
            --name wp-container \
            --network wp-network \
            wordpress

      - name: Install WordPress
        run: |
          docker run -i --rm \
            --volumes-from wp-container \
            --network wp-network \
            wordpress:cli core install \
              --url=localhost \
              --title=test \
              --admin_user=admin \
              --admin_password=admin \
              --admin_email=foo@bar.com

      - name: Install Relative URL plugin
        run: |
          docker run -i --rm \
            --volumes-from wp-container \
            --user xfs \
            --network wp-network \
            wordpress:cli plugin install relative-url \
              --activate \

      - name: Install WooCommerce plugin
        run: |
          docker run -i --rm \
            --volumes-from wp-container \
            --user xfs \
            --network wp-network \
            wordpress:cli plugin install woocommerce \
              --activate \

      - name: copy Install Billmate Payment Gateway plugin
        run: docker cp ${{ github.workspace }}/src wp-container:/var/www/html

      - name: Install Billmate Payment Gateway (this) plugin
        run: |
          docker run -it --rm \
            --volumes-from wp-container \
            --user xfs \
            --network wp-network \
            wordpress:cli plugin install /var/www/html/src \
              --activate

      - name: Ping local WP instance (localhost)
        run: |
          ping -c 4 localhost