name: Docker Compose Actions Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up network
        run: docker network create wp-network

      - name: Set up database
        run: |
          docker run -d \
            -e MYSQL_ROOT_PASSWORD=1234 \
            -e MYSQL_DATABASE=wordpress \
            --name db \
            --network wp-network \
            mysql:5.7

      - name: Setup WordPress
        run: |
          docker run -d \
            -e WORDPRESS_DB_HOST=db:3306 \
            -e WORDPRESS_DB_USER=root \
            -e WORDPRESS_DB_PASSWORD=1234 \
            -e WORDPRESS_DB_NAME=wordpress \
            -e WORDPRESS_CONFIG_EXTRA="define('WP_SITEURL', 'http://' . \$_SERVER['HTTP_HOST']); define('WP_HOME', 'http://' . \$_SERVER['HTTP_HOST']);" \
            --name wp-container \
            --network wp-network \
            wordpress

      - name: Install WordPress
        run: |
          docker run -i --rm \
            --volumes-from wp-container \
            --network wp-network \
            wordpress:cli core install \
              --url=localhost \
              --title=test \
              --admin_user=admin \
              --admin_password=admin \
              --admin_email=foo@bar.com